name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-20.04

    strategy:
      fail-fast: false
      matrix:
        php: [8.0, 8.1, 8.2, 8.3]
        coverage: ["false"]
        include:
        - php: 8.4
          coverage: "true" # Collecting coverage reports only once

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup PHP & Composer
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php }}
        tools: composer:v2

    - name: Install dependencies
      run: composer install --no-interaction --no-suggest

    - name: PHPUnit
      env:
        COVERAGE: ${{ matrix.coverage }}
      run: |
        [ $COVERAGE = "true" ] \
          ./vendor/bin/phpunit --coverage-clover coverage.xml \
          || ./vendor/bin/phpunit

    - name: Psalm
      run: |
        ./vendor/bin/psalm --shepherd

    - name: Push coverage report to codecov
      uses: codecov/codecov-action@v5
